// Generated by CoffeeScript 1.6.3
(function() {
  var generateQRCode;

  $(function() {
    $('textarea').bind('keyup', generateQRCode);
    $('#triggerCreate').bind('click', generateQRCode);
    $(window).bind('hashchange', function() {
      var text;
      text = window.location.hash.substring(1);
      $('textarea').val(decodeURIComponent(text));
      return generateQRCode();
    });
    $('a', '#download').bind('click', function() {
      return window.location.href = $('canvas', '#qrarea')[0].toDataURL('image/png').replace('image/png', 'image/octet-stream');
    });
    if (window.location.hash) {
      $(window).trigger('hashchange');
    }
    return generateQRCode();
  });

  generateQRCode = function() {
    var text;
    text = $('textarea').val();
    $('#qrarea').empty();
    return $('#qrarea').qrcode({
      text: text,
      width: 512,
      height: 512
    });
  };

}).call(this);
